In [4]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results__.html
/kaggle/input/notebooks/saurav9786/time-series-tutorial/ts1.csv
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__notebook__.ipynb
/kaggle/input/notebooks/saurav9786/time-series-tutorial/GDPIndia.obj
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__output__.json
/kaggle/input/notebooks/saurav9786/time-series-tutorial/custom.css
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___80_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___138_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___328_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___319_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___374_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___233_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___170_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___40_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___147_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___398_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___213_2.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___140_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___79_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___365_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___25_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___302_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___14_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___147_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___101_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___143_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___22_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___64_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___199_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___354_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___372_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___133_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___201_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___207_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___159_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___63_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___404_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___175_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___116_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___325_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___240_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___363_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___222_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___121_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___43_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___402_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___350_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___332_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___54_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___294_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___183_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___173_5.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___37_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___254_4.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___254_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___321_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___192_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___52_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___215_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___150_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___309_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___366_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___29_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___378_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___83_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___274_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___159_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___97_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___90_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___169_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___335_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___34_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___370_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___380_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___74_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___173_3.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___281_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___324_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___254_2.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___247_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___318_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___96_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___254_3.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___376_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___135_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___329_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___352_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___260_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___100_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___94_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___92_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___339_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___267_0.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___331_1.png
/kaggle/input/notebooks/saurav9786/time-series-tutorial/__results___files/__results___173_1.png

In [18]:
df = pd.read_csv('/kaggle/input/notebooks/saurav9786/time-series-tutorial/ts1.csv')
print('done')

done

In [17]:
df.head()

        Month  #Passengers
0  1949-01-01          112
1  1949-02-01          118
2  1949-03-01          132
3  1949-04-01          129
4  1949-05-01          121

In [19]:
df.head(21)

         Month  #Passengers
0   1949-01-01          112
1   1949-02-01          118
2   1949-03-01          132
3   1949-04-01          129
4   1949-05-01          121
5   1949-06-01          135
6   1949-07-01          148
7   1949-08-01          148
8   1949-09-01          136
9   1949-10-01          119
10  1949-11-01          104
11  1949-12-01          118
12  1950-01-01          115
13  1950-02-01          126
14  1950-03-01          141
15  1950-04-01          135
16  1950-05-01          125
17  1950-06-01          149
18  1950-07-01          170
19  1950-08-01          170
20  1950-09-01          158

In [20]:
df.tail(21)

          Month  #Passengers
123  1959-04-01          396
124  1959-05-01          420
125  1959-06-01          472
126  1959-07-01          548
127  1959-08-01          559
128  1959-09-01          463
129  1959-10-01          407
130  1959-11-01          362
131  1959-12-01          405
132  1960-01-01          417
133  1960-02-01          391
134  1960-03-01          419
135  1960-04-01          461
136  1960-05-01          472
137  1960-06-01          535
138  1960-07-01          622
139  1960-08-01          606
140  1960-09-01          508
141  1960-10-01          461
142  1960-11-01          390
143  1960-12-01          432

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Month        144 non-null    object
 1   #Passengers  144 non-null    int64
dtypes: int64(1), object(1)
memory usage: 2.4+ KB

In [22]:
df.describe()

       #Passengers
count   144.000000
mean    280.298611
std     119.966317
min     104.000000
25%     180.000000
50%     265.500000
75%     360.500000
max     622.000000

In [23]:
df.isnull()

     Month  #Passengers
0    False        False
1    False        False
2    False        False
3    False        False
4    False        False
..     ...          ...
139  False        False
140  False        False
141  False        False
142  False        False
143  False        False

[144 rows x 2 columns]

In [34]:
df.isnull().count()

Month          144
#Passengers    144
dtype: int64